import '../../styles/globals.css';
import '../../styles/generated.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            if (!sessionStorage.getItem('reloaded')) {
                                sessionStorage.setItem('reloaded', 'true');
                                if (performance.navigation.type === 1 || performance.navigation.type === 0) {
                                window.location.reload();
                                }
                            } else {
                                sessionStorage.removeItem('reloaded');
                            }
                            `,
                    }}
                />
            </body>
        </html>
    );
}
